version: '3.9'

services:
  poetry:
    image: poetry:${PYTHON_VERSION}
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    container_name: poetry${PYTHON_VERSION}
    command: "${POETRY_COMMAND}"
    user: "${UID}:${GID}"
    volumes:
      - ${POETRY_CACHE_DIR}:/tmp/poetry_cache:rw
      - ${POETRY_PROJECT_DIR}:/app:rw
