version: '3.9'

services:
  poetry:
    image: poetry:${PYTHON_VERSION}
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    container_name: poetry${PYTHON_VERSION}
    command: "${POETRY_COMMANDS}"
    user: "1000:1000"
    volumes:
      - ~/.cache/pypoetry:/tmp/poetry_cache:rw
      - /home/alberto/src/tfg:/app:rw
