version: '3.9'

services:
  poetry:
    image: poetry:${PYTHON_VERSION}
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    container_name: poetry${PYTHON_VERSION}
    command: "${POETRY_COMMAND}"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ${POETRY_CACHE_DIR:-~/.cache/pypoetry}:/tmp/poetry_cache:rw
      - ${POETRY_PROJECT_DIR}:/app:rw
